# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  requestBody:
    resetPassword:
      send: 
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  required: true
                  type: string
      verified:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  required: true
                  type: string