# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responses:
    resetPassword:
      send: 
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  required: true
                  type: string
                  example: authToken
                success:
                  type: boolean
                  example: true
                error:
                  type: any
                  example: Null
      verifyToken: 
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  $ref: '#/components/schemas/Users'
                success:
                  type: boolean
                  example: true
                error:
                  type: any
                  example: Null