# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responseBody:
    UserProduct:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserProduct'
    UserProducts:
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/responses/http/success'
              - type: object
                properties:
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProduct'