# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/authentication/bearer-authentication/
# 

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
