components:
  responses:
    http:
      success:
        type: object
        properties:
          success:
            type: boolean
            default: false
          error:
            type: any
            default: null
      failed:
        type: object
        properties:
          success:
            type: boolean
            default: false
          error:
            type: any
            default: null