# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  requestBody:
    Product:
      form:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductParam'
      published:
        content:
          application/json:
            schema:
              type: object
              properties:
                status: 
                  type: boolean
                  default: false
                  example: true
  requestParams:
    Product:
      id:
        in: path
        name: productId
        schema:
          type: string
          required: true