# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  requestBody:
    Product:
      form:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductParam'