# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  models:
    User:
      _id:
        type: string
        required: true,
        description: 'id of the user/customer.'
      name:
        type: string
        description: 'fullName or display name of the user/customer.'
      role:
        type: string
        description: 'role name of the user/customer.'
        default: 'user'
      password:
        type: string
        description: 'password of the user/customer.'
      stripeCustomerId:
        type: string
        description: 'customerId from payment gateway(stripe).'
      email:
        $ref: '#/components/schemas/FieldVerificationEntity'
      mobileNumber:
        $ref: '#/components/schemas/FieldVerificationEntity'
      createdAt:
        $ref: '#/components/schemas/FieldCreatedAt'
      updatedAt:
        $ref: '#/components/schemas/FieldUpdatedAt'
        