# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responses:
    Users:
      description: OK
      content:
        application/json:
          schema: 
            type: object
            properties:
              username:
                type: string
              password:
                type: string