# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responses:
    User:
      Detail:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/responses/http/success'
                - type: object
                  properties:
                    result:
                      $ref: '#/components/schemas/Users'
      List:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/responses/http/success'
                - type: object
                  properties:
                    result:
                      type: array
                      items:
                        $ref: '#/components/schemas/Users'