# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  schemas:
    Users:
      type: object
      properties:
        _id:
          $ref: '#/components/schemas/FieldId'
        name:
          type: string
        role:
          type: string
        # password:
        #   type: string
        stripeCustomerId:
          type: string
        email:
          $ref: '#/components/schemas/FieldVerificationEntity'
        mobileNumber:
          $ref: '#/components/schemas/FieldVerificationEntity'
        createdAt:
          $ref: '#/components/schemas/FieldCreatedAt'
        updatedAt:
          $ref: '#/components/schemas/FieldUpdatedAt'
        