# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  requestBody:
    SignIn:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                required: true
                type: string
              password:
                type: string