# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  requestBody:
    SignUp:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                required: true
                type: string
              email:
                required: true
                type: string
              password:
                required: true
                type: string