# 
# References:
# https://swagger.io/docs/specification/components/
# https://swagger.io/docs/specification/data-models/
# https://swagger.io/docs/specification/using-ref/
# 

components:
  responses:
    User:
      resendOTP:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/responses/http/success'
                - type: object
                  properties:
                    result:
                      type: object
                      properties:
                        code:
                          type: string
    signUp:
      $ref: '#/components/responses/SignIn'
    verifiedSignInToken:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              result:
                $ref: '#/components/schemas/User'
              error:
                type: null
    