import swaggerJSDoc from 'swagger-jsdoc';
import { BACKEND_HOST } from '../../api/utils/constants';
console.log('BACKEND_HOST :>> ', BACKEND_HOST);
const options = {
    // swaggerOptions: {
    //     url: 'http://petstore.swagger.io/v3/swagger.json'
    // },
    swaggerDefinition: {
        openapi: "3.0.0",
        info: {
            title: 'Simple API',
            version: '1.0.0',
            description: 'Test Express APi with autogenerated swagger doc',
        },
        host: `${BACKEND_HOST}`,
        basePath: '/v1',
        // servers: [`${BACKEND_HOST}`],
    },
    apis: [
        './src/api/routes/**/*.ts',
        './src/config/swagger/**/*.yml',
    ],
};
export default swaggerJSDoc(options);